server:
  port: 4000
  servlet:
    context-path: /api/v1/hele-desk

spring:
  application:
    name: AI-Help-Desk
  mail:
    host: smtp.gmail.com
    port: 587
    username: "govindaekbote7@gmail.com"
    password: "ppjxtkwchxhlybyd"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/ai_help_desk
    username: root
    password: Govinda@1997
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: ldkfdkfdsdslfdsklfdsklfkldfjkdfnfdklslklfdsmkl


logging:
  file:
    name: ai-help-desk.log
  level:
    root: INFO
    org.springframework.web: DEBUG

